"""
Django settings for ahmia project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# You can filter terms and/or show some helpful content to the user
FILTER_TERMS_AND_SHOW_HELP = [
    line[3:-5].strip()
    for line in open("/etc/nginx/banned_terms.map")
    if line.startswith('"~*') and line.strip().endswith('" 1;')
]

# Elasticsearch settings using environment variables for sensitive information
#I.e, ELASTICSEARCH_SERVER = config('ES_URL', default="https://localhost:9200/")
ELASTICSEARCH_SERVER = config('ES_URL', default="https://10.0.0.2:9200/")
ELASTICSEARCH_INDEX = 'latest-tor'
ELASTICSEARCH_USERNAME = config('ES_USERNAME', default='elastic')
ELASTICSEARCH_PASSWORD = config('ES_PASSWORD', default='password12345')
ELASTICSEARCH_CA_CERTS = config('ES_CA_CERTS', default='/etc/elasticsearch/certs/http_ca.crt')
ELASTICSEARCH_TIMEOUT = config('ELASTICSEARCH_TIMEOUT', cast=int, default=60)
VERIFY_CERT = config('VERIFY_CERT', cast=bool, default=False)

SALT = config('SALT', default='secret_salt_value')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_2r8zw$f^8)j1n8o*3va^9wt784fqtn%^t1!4*lr2!s#1k7zyh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.ahmia.fi',   # Allow domain and subdomains
    '.ahmia.fi.',  # Also allow FQDN and subdomains
    '.juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion',
    '.juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion.',
    '46.19.38.63'
]

HELP_DOMAINS = [
    'webropolsurveys.com',
    'pelastakaalapset.fi',
    'mielenterveystalo.fi',
    'iterapi.se',
    'redirectionprogram.com',
    'troubled-desire.com',
    'redirhr3cvqeq2xglvjfd2uiilycwn7nmu3rtnuwv7zthzxjrj7wf3yd.onion',
    'helplinkshtttptrdoukunonaiansstlrx4yherxk6azymviqtgle2yd.onion',
    '6wvybf7ub3xk5ow66wt7os3aovbzoo2eei6vjirvhvvkmqg4alnezzid.onion'
]

# Application definition

INSTALLED_APPS = [
    'ahmia',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ahmia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['ahmia/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'ahmia_tags': 'ahmia.template_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'ahmia.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "onionAddDatabase",
        "OPTIONS": {
            "timeout": 180,
            "isolation_level": None,
            "init_command": "PRAGMA journal_mode=WAL;"
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'

# Define the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = BASE_DIR / 'ahmia' / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'ahmia' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
